CREATE DATABASE IF NOT EXISTS review;

USE review;

CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL);

CREATE TABLE movie_reviews (id INT AUTO_INCREMENT PRIMARY KEY,movie_name VARCHAR(100) NOT NULL,movie_release_date DATE NOT NULL,review TEXT NOT NULL);
